name: kawaibox
description: Launcher for 18+ anime content and games
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_analytics: ^11.4.4

  # State management
  provider: ^6.0.5
  flutter_bloc: ^9.1.0

  # UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0

  # Navigation
  go_router: ^14.8.1

  # Utilities
  http: ^1.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  path_provider: ^2.0.15

  # Video player
  video_player: ^2.7.0
  chewie: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/